version: '3.6'
services:
  wallet:
    container_name: '${STAGE}-${APP_NAME}-wallet'
    build: ./wallet
    ports:
      - '9999:8888'
    volumes:
      - ${WALLET_DATA}:/opt/application/data
  postgres:
    container_name: '${STAGE}-${APP_NAME}-postgres'
    image: postgres:13.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
  hapi:
    container_name: '${STAGE}-${APP_NAME}-hapi'
    build: ./hapi
    ports:
      - '9090:9090'
    volumes:
      - ./modules/hapi:/app/node_modules
      - type: bind
        source: ./hapi
        target: /app
    working_dir: /app
    command: bash -c "pm2-runtime app.json --watch"
    environment:
      HAPI_EOS_API_NETWORK_NAME: '${HAPI_EOS_API_NETWORK_NAME}'
      HAPI_EOS_API_ENDPOINT: '${HAPI_EOS_API_ENDPOINT}'
      HAPI_EOS_STATE_HISTORY_PLUGIN_ENDPOINT: '${HAPI_EOS_STATE_HISTORY_PLUGIN_ENDPOINT}'
      HAPI_EOS_API_CHAIN_ID: '${HAPI_EOS_API_CHAIN_ID}'
      HAPI_EOS_BASE_ACCOUNT: '${HAPI_EOS_BASE_ACCOUNT}'
      HAPI_EOS_BASE_ACCOUNT_PASSWORD: '${HAPI_EOS_BASE_ACCOUNT_PASSWORD}'
      HAPI_EOS_MECHANICS_ACCOUNT: '${HAPI_EOS_MECHANICS_ACCOUNT}'
      HAPI_EOS_MECHANICS_PASSWORD: '${HAPI_EOS_MECHANICS_PASSWORD}'
      HAPI_EOS_MECHANICS_INCLUDE_TRANSACTION: '${HAPI_EOS_MECHANICS_INCLUDE_TRANSACTION}'
      HAPI_EOS_WALLET_URL: '${HAPI_EOS_WALLET_URL}'
      HAPI_EOS_EXCHANGE_RATE_API: '${HAPI_EOS_EXCHANGE_RATE_API}'
      HAPI_EOS_BP_JSON_ON_CHAIN: '${HAPI_EOS_BP_JSON_ON_CHAIN}'
      HAPI_EOS_BP_JSON_ON_CHAIN_CONTRACT: '${HAPI_EOS_BP_JSON_ON_CHAIN_CONTRACT}'
      HAPI_EOS_BP_JSON_ON_CHAIN_TABLE: '${HAPI_EOS_BP_JSON_ON_CHAIN_TABLE}'
      HAPI_EOS_BP_JSON_ON_CHAIN_SCOPE: '${HAPI_EOS_BP_JSON_ON_CHAIN_SCOPE}'
      HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
      HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
      HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
      HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
      HAPI_DATABASE_URL: '${HAPI_DATABASE_URL}'
      HAPI_SYNC_PRODUCERS_INTERVAL: '${HAPI_SYNC_PRODUCERS_INTERVAL}'
      HAPI_SYNC_PRODUCER_INFO_INTERVAL: '${HAPI_SYNC_PRODUCER_INFO_INTERVAL}'
      HAPI_SYNC_PRODUCER_CPU_INTERVAL: '${HAPI_SYNC_PRODUCER_CPU_INTERVAL}'
      HAPI_COINGECKO_API_TOKEN_ID: '${HAPI_COINGECKO_API_TOKEN_ID}'
      HAPI_SYNC_STATS_INTERVAL: '${HAPI_SYNC_STATS_INTERVAL}'
      HAPI_SYNC_SCHEDULE_HISTORY_INTERVAL: '${HAPI_SYNC_SCHEDULE_HISTORY_INTERVAL}'
  hasura:
    container_name: '${STAGE}-${APP_NAME}-hasura'
    image: hasura/graphql-engine:v2.0.0-alpha.11.cli-migrations-v2
    ports:
      - '8585:8080'
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
      HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
      HASURA_GRAPHQL_ACTION_BASE_URL: '${HASURA_GRAPHQL_ACTION_BASE_URL}'
  webapp:
    container_name: '${STAGE}-${APP_NAME}-webapp'
    image: node:14.2.0
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - ./modules/webapp:/app/node_modules
      - type: bind
        source: ./webapp
        target: /app
    working_dir: /app
    command: bash -c "yarn && yarn start"
    environment:
      REACT_APP_TITLE: '${REACT_APP_TITLE}'
      REACT_APP_DEFAULT_PRODUCER_LOGO: '${REACT_APP_DEFAULT_PRODUCER_LOGO}'
      REACT_APP_FOOTER_LINKS: '${REACT_APP_FOOTER_LINKS}'
      REACT_APP_EOS_RATE_LINK: '${REACT_APP_EOS_RATE_LINK}'
      REACT_APP_USE_REWARDS: '${REACT_APP_USE_REWARDS}'
      REACT_APP_USE_VOTES: '${REACT_APP_USE_VOTES}'
      REACT_APP_USE_CPU_BENCHMARK: '${REACT_APP_USE_CPU_BENCHMARK}'
      REACT_APP_HASURA_URL: '${REACT_APP_HASURA_URL}'
      REACT_APP_EOS_API_NETWORK_NAME: '${REACT_APP_EOS_API_NETWORK_NAME}'
      REACT_APP_EOS_API_NETWORK_LABEL: '${REACT_APP_EOS_API_NETWORK_LABEL}'
      REACT_APP_EOS_API_NETWORK_LOGO: '${REACT_APP_EOS_API_NETWORK_LOGO}'
      REACT_APP_EOS_INCLUDE_TRANSACTION: '${REACT_APP_EOS_INCLUDE_TRANSACTION}'
      REACT_APP_EOS_API_HOST: '${REACT_APP_EOS_API_HOST}'
      REACT_APP_EOS_API_PORT: '${REACT_APP_EOS_API_PORT}'
      REACT_APP_EOS_API_PROTOCOL: '${REACT_APP_EOS_API_PROTOCOL}'
      REACT_APP_EOS_CHAIN_ID: '${REACT_APP_EOS_CHAIN_ID}'
      REACT_APP_EOS_USE_BP_JSON_ON_CHAIN: '${REACT_APP_EOS_USE_BP_JSON_ON_CHAIN}'
      REACT_APP_EOS_BP_JSON_ON_CHAIN_CONTRACT: '${REACT_APP_EOS_BP_JSON_ON_CHAIN_CONTRACT}'
      REACT_APP_EOS_BP_JSON_ON_CHAIN_TABLE: '${REACT_APP_EOS_BP_JSON_ON_CHAIN_TABLE}'
      REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE: '${REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE}'
      REACT_APP_TOKEN_SYMBOL: '${REACT_APP_TOKEN_SYMBOL}'
      REACT_APP_NETWORK_URL: '${REACT_APP_NETWORK_URL}'
      REACT_APP_DISABLED_MENU_ITEMS: '${REACT_APP_DISABLED_MENU_ITEMS}'
      REACT_APP_BLOCK_EXPLORER_URL: '${REACT_APP_BLOCK_EXPLORER_URL}'
      REACT_APP_TAG: '${REACT_APP_TAG}'
volumes:
  postgres_data: