name: Build images for mainnet environment

on:
  push:
    tags:
      - mainnet-v*

jobs:
  create-mainnet-image:
    runs-on: ubuntu-latest
    environment: mainnet
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to docker registry
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login \
            --username ${{ secrets.DOCKER_HUB_USER }} \
            --password-stdin

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # webapp

          PORT: '80'
          REACT_APP_TITLE: 'EOS Mainnet Network Dashboard'
          REACT_APP_TAG: ${{ github.ref }}
          REACT_APP_DEFAULT_PRODUCER_LOGO: 'https://bloks.io/img/eosio.png'
          REACT_APP_EOS_RATE_LINK: 'https://eosrate.io'
          REACT_APP_USE_REWARDS: 'true'
          REACT_APP_USE_VOTES: 'true'
          REACT_APP_USE_BLOCK_PRODUCER_AGREEMENT_CONTRACT: 'true'
          REACT_APP_HASURA_URL: 'https://graphql-mainnet.eosio.online/v1/graphql'
          REACT_APP_EOS_API_HOST: 'api.eosio.cr'
          REACT_APP_EOS_API_PORT: '443'
          REACT_APP_EOS_API_PROTOCOL: 'https'
          REACT_APP_EOS_CHAIN_ID: 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906'
          REACT_APP_EOS_DEFAULT_EXCHANGE_RATE: '2.50'
          REACT_APP_EOS_DEFAULT_EXCHANGE_RATE_API: ${{ secrets.REACT_APP_EOS_DEFAULT_EXCHANGE_RATE_API }}
          REACT_APP_EOS_USE_BP_JSON_ON_CHAIN: 'false'
          REACT_APP_EOS_BP_JSON_ON_CHAIN_CONTRACT: ${{ secrets.REACT_APP_EOS_BP_JSON_ON_CHAIN_CONTRACT }}
          REACT_APP_EOS_BP_JSON_ON_CHAIN_TABLE: ${{ secrets.REACT_APP_EOS_BP_JSON_ON_CHAIN_TABLE }}
          REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE: ${{ secrets.REACT_APP_EOS_BP_JSON_ON_CHAIN_SCOPE }}
          REACT_APP_EOS_API_NETWORK_NAME: 'mainnet'
          REACT_APP_EOS_API_NETWORK_LABEL: 'EOS Mainnet'
          REACT_APP_EOS_API_NETWORK_LOGO: 'https://bloks.io/img/eosio.png'
          REACT_APP_TOKEN_SYMBOL: ${{ secrets.REACT_APP_TOKEN_SYMBOL }}
          REACT_APP_NETWORK_URL: '[{"label":"EOS Mainnet","value":"https://mainnet.eosio.online"},{"label":"LACChain EOSIO","value":"https://lacchain.eosio.online"},{"label":"Jungle Testnet","value":"https://jungle.eosio.online"},{"label":"Proton Testnet","value":"https://proton-testnet.eosio.online"},{"label":"Telos Testnet","value":"https://telos-testnet.eosio.online"}]'
          REACT_APP_DISABLED_MENU_ITEMS: '["/missed-blocks", "/cpu-benchmark","/block-distribution"]'
          REACT_APP_BLOCK_EXPLORER_URL: 'https://bloks.io/transaction/${transaction}'

      - name: Build and deploy kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          NAMESPACE: mainnet-dashboard
          INGRESS_HOST: mainnet.eosio.online
          INGRESS_GRAPHQL_HOST: graphql-mainnet.eosio.online
          # webapp
          REACT_APP_EOS_API_NETWORK_NAME: 'mainnet'
          # postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_DATA: ${{ secrets.POSTGRES_DATA }}
          # hapi
          HAPI_EOS_API_ENDPOINT: 'https://api.eosio.cr'
          HAPI_EOS_API_CHAIN_ID: 'e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473'
          HAPI_EOS_BASE_ACCOUNT: ${{ secrets.HAPI_EOS_BASE_ACCOUNT }}
          HAPI_EOS_BASE_ACCOUNT_PASSWORD: ${{ secrets.HAPI_EOS_BASE_ACCOUNT_PASSWORD }}
          HAPI_EOS_MECHANICS_ACCOUNT: ${{ secrets.HAPI_EOS_MECHANICS_ACCOUNT }}
          HAPI_EOS_MECHANICS_PASSWORD: ${{ secrets.HAPI_EOS_MECHANICS_PASSWORD }}
          HAPI_EOS_WALLET_URL: http://dashboard-wallet:8888
          HAPI_EOS_BP_JSON_ON_CHAIN: 'false'
          HAPI_EOS_BP_JSON_ON_CHAIN_CONTRACT: ''
          HAPI_EOS_BP_JSON_ON_CHAIN_TABLE: ''
          HAPI_EOS_BP_JSON_ON_CHAIN_SCOPE: ''
          HAPI_HASURA_URL: 'http://dashboard-hasura:8080/v1/graphql'
          HAPI_HASURA_ADMIN_SECRET: ${{ secrets.HAPI_HASURA_ADMIN_SECRET }}
          HAPI_SERVER_PORT: '9090'
          HAPI_SERVER_ADDRESS: '0.0.0.0'
          HAPI_DATABASE_URL: ${{ secrets.HAPI_DATABASE_URL }}
          HAPI_SYNC_PRODUCERS_INTERVAL: '86400'
          HAPI_SYNC_PRODUCER_INFO_INTERVAL: '1'
          HAPI_SYNC_PRODUCER_CPU_INTERVAL: '6'
          HAPI_SYNC_SCHEDULE_HISTORY_INTERVAL: 86400
          HAPI_EOS_EXCHANGE_RATE_API: https://api.coingecko.com/api/v3/simple/price?ids=eos&vs_currencies=usd
          HAPI_COINGECKO_API_TOKEN_ID: eos
          # hasura
          HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
          HASURA_GRAPHQL_ACTION_BASE_URL: http://dashboard-hapi:9090

      - name: Setup and deploy kubernetes environment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: mainnet-dashboard
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes
